//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acces denied.
        /// </summary>
        public static string AccesDenied {
            get {
                return ResourceManager.GetString("AccesDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your language:.
        /// </summary>
        public static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file type:.
        /// </summary>
        public static string ChangeLogsFormat {
            get {
                return ResourceManager.GetString("ChangeLogsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Type:.
        /// </summary>
        public static string ChangeLogsFormat_Actual {
            get {
                return ResourceManager.GetString("ChangeLogsFormat.Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it correct?.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Confirm_No {
            get {
                return ResourceManager.GetString("Confirm.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Confirm_Yes {
            get {
                return ResourceManager.GetString("Confirm.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files....
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter save destination path:.
        /// </summary>
        public static string CreateSave_Dest {
            get {
                return ResourceManager.GetString("CreateSave.Dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination path.
        /// </summary>
        public static string CreateSave_DestPath {
            get {
                return ResourceManager.GetString("CreateSave.DestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many backups have already been created.
        /// </summary>
        public static string CreateSave_MaxSaves {
            get {
                return ResourceManager.GetString("CreateSave.MaxSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter save name:.
        /// </summary>
        public static string CreateSave_Name {
            get {
                return ResourceManager.GetString("CreateSave.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter save source path:.
        /// </summary>
        public static string CreateSave_Src {
            get {
                return ResourceManager.GetString("CreateSave.Src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select source path.
        /// </summary>
        public static string CreateSave_SrcPath {
            get {
                return ResourceManager.GetString("CreateSave.SrcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose save type:.
        /// </summary>
        public static string CreateSave_Type {
            get {
                return ResourceManager.GetString("CreateSave.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential Save.
        /// </summary>
        public static string CreateSave_Type_Differential {
            get {
                return ResourceManager.GetString("CreateSave.Type.Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Save.
        /// </summary>
        public static string CreateSave_Type_Full {
            get {
                return ResourceManager.GetString("CreateSave.Type.Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, please restart app..
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to menu.
        /// </summary>
        public static string Forms_Back {
            get {
                return ResourceManager.GetString("Forms.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Forms_Exit {
            get {
                return ResourceManager.GetString("Forms.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save created successfully!.
        /// </summary>
        public static string Header_CreateSaveSuccess {
            get {
                return ResourceManager.GetString("Header.CreateSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available:.
        /// </summary>
        public static string Header_NoUpToDate {
            get {
                return ResourceManager.GetString("Header.NoUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The save is already running.
        /// </summary>
        public static string Header_SaveAlreadyRunning {
            get {
                return ResourceManager.GetString("Header.SaveAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save deleted successfully.
        /// </summary>
        public static string Header_SaveDeleted {
            get {
                return ResourceManager.GetString("Header.SaveDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successfully renamed.
        /// </summary>
        public static string Header_SaveRenamed {
            get {
                return ResourceManager.GetString("Header.SaveRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters saved successfully.
        /// </summary>
        public static string Header_SettingsSaved {
            get {
                return ResourceManager.GetString("Header.SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasySave is up-to-date..
        /// </summary>
        public static string Header_UpToDate {
            get {
                return ResourceManager.GetString("Header.UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a save.
        /// </summary>
        public static string HomeMenu_Create {
            get {
                return ResourceManager.GetString("HomeMenu.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a save.
        /// </summary>
        public static string HomeMenu_Delete {
            get {
                return ResourceManager.GetString("HomeMenu.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a save.
        /// </summary>
        public static string HomeMenu_Edit {
            get {
                return ResourceManager.GetString("HomeMenu.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a save.
        /// </summary>
        public static string HomeMenu_Load {
            get {
                return ResourceManager.GetString("HomeMenu.Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string HomeMenu_Settings {
            get {
                return ResourceManager.GetString("HomeMenu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CryptoSoft Settings:.
        /// </summary>
        public static string HomeMenu_Settings_CryptoSoft {
            get {
                return ResourceManager.GetString("HomeMenu.Settings.CryptoSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an action:.
        /// </summary>
        public static string HomeMenu_Title {
            get {
                return ResourceManager.GetString("HomeMenu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to EasySave, the easiest to use backup application. To save data, simply go to the &quot;Create Save&quot; selection. If you have any problems please contact us at easysave.help@outlook.com.
        /// </summary>
        public static string HomePresentation {
            get {
                return ResourceManager.GetString("HomePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most practical backup application.
        /// </summary>
        public static string HomeSubtitle {
            get {
                return ResourceManager.GetString("HomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to EasySave.
        /// </summary>
        public static string HomeWelcome {
            get {
                return ResourceManager.GetString("HomeWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Lang_en_US {
            get {
                return ResourceManager.GetString("Lang.en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Lang_fr_FR {
            get {
                return ResourceManager.GetString("Lang.fr-FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Lang_it_IT {
            get {
                return ResourceManager.GetString("Lang.it-IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Lang_ru_RU {
            get {
                return ResourceManager.GetString("Lang.ru-RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Path | .
        /// </summary>
        public static string Path_Invalid {
            get {
                return ResourceManager.GetString("Path.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup summary:.
        /// </summary>
        public static string Save_Info {
            get {
                return ResourceManager.GetString("Save.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the save?.
        /// </summary>
        public static string Save_Run {
            get {
                return ResourceManager.GetString("Save.Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your saves :.
        /// </summary>
        public static string SaveMenu_Title {
            get {
                return ResourceManager.GetString("SaveMenu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CryptoSoft Extensions:.
        /// </summary>
        public static string Settings_Extensions {
            get {
                return ResourceManager.GetString("Settings.Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CryptoSoft Secret:.
        /// </summary>
        public static string Settings_Secret {
            get {
                return ResourceManager.GetString("Settings.Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string SettingsMenu_ChangeLanguage {
            get {
                return ResourceManager.GetString("SettingsMenu.ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file format.
        /// </summary>
        public static string SettingsMenu_LogsFormat {
            get {
                return ResourceManager.GetString("SettingsMenu.LogsFormat", resourceCulture);
            }
        }
    }
}
