//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Acces denied.
        /// </summary>
        public static string AccesDenied {
            get {
                return ResourceManager.GetString("AccesDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select all.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose your language:.
        /// </summary>
        public static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select file type:.
        /// </summary>
        public static string ChangeLogsFormat {
            get {
                return ResourceManager.GetString("ChangeLogsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current Type:.
        /// </summary>
        public static string ChangeLogsFormat_Actual {
            get {
                return ResourceManager.GetString("ChangeLogsFormat.Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is it correct?.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string Confirm_No {
            get {
                return ResourceManager.GetString("Confirm.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Confirm_Yes {
            get {
                return ResourceManager.GetString("Confirm.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copying files....
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter save destination path:.
        /// </summary>
        public static string CreateSave_Dest {
            get {
                return ResourceManager.GetString("CreateSave.Dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select destination path.
        /// </summary>
        public static string CreateSave_DestPath {
            get {
                return ResourceManager.GetString("CreateSave.DestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Too many backups have already been created.
        /// </summary>
        public static string CreateSave_MaxSaves {
            get {
                return ResourceManager.GetString("CreateSave.MaxSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter save name:.
        /// </summary>
        public static string CreateSave_Name {
            get {
                return ResourceManager.GetString("CreateSave.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter save source path:.
        /// </summary>
        public static string CreateSave_Src {
            get {
                return ResourceManager.GetString("CreateSave.Src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select source path.
        /// </summary>
        public static string CreateSave_SrcPath {
            get {
                return ResourceManager.GetString("CreateSave.SrcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose save type:.
        /// </summary>
        public static string CreateSave_Type {
            get {
                return ResourceManager.GetString("CreateSave.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential Save.
        /// </summary>
        public static string CreateSave_Type_Differential {
            get {
                return ResourceManager.GetString("CreateSave.Type.Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full Save.
        /// </summary>
        public static string CreateSave_Type_Full {
            get {
                return ResourceManager.GetString("CreateSave.Type.Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured, please restart app..
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [NAME] backup stopped.
        /// </summary>
        public static string Exception_Run_SP_Title {
            get {
                return ResourceManager.GetString("Exception.Run-SP-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The software &quot;[PROCESS]&quot; is running.
        /// </summary>
        public static string Exception_Running_Software_Package {
            get {
                return ResourceManager.GetString("Exception.Running-Software-Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return to menu.
        /// </summary>
        public static string Forms_Back {
            get {
                return ResourceManager.GetString("Forms.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        public static string Forms_Exit {
            get {
                return ResourceManager.GetString("Forms.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save created successfully!.
        /// </summary>
        public static string Header_CreateSaveSuccess {
            get {
                return ResourceManager.GetString("Header.CreateSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new version is available:.
        /// </summary>
        public static string Header_NoUpToDate {
            get {
                return ResourceManager.GetString("Header.NoUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The save is already running.
        /// </summary>
        public static string Header_SaveAlreadyRunning {
            get {
                return ResourceManager.GetString("Header.SaveAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save deleted successfully.
        /// </summary>
        public static string Header_SaveDeleted {
            get {
                return ResourceManager.GetString("Header.SaveDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save successfully renamed.
        /// </summary>
        public static string Header_SaveRenamed {
            get {
                return ResourceManager.GetString("Header.SaveRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parameters saved successfully.
        /// </summary>
        public static string Header_SettingsSaved {
            get {
                return ResourceManager.GetString("Header.SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EasySave is up-to-date..
        /// </summary>
        public static string Header_UpToDate {
            get {
                return ResourceManager.GetString("Header.UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a save.
        /// </summary>
        public static string HomeMenu_Create {
            get {
                return ResourceManager.GetString("HomeMenu.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a save.
        /// </summary>
        public static string HomeMenu_Delete {
            get {
                return ResourceManager.GetString("HomeMenu.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit a save.
        /// </summary>
        public static string HomeMenu_Edit {
            get {
                return ResourceManager.GetString("HomeMenu.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string HomeMenu_Home {
            get {
                return ResourceManager.GetString("HomeMenu.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load a save.
        /// </summary>
        public static string HomeMenu_Load {
            get {
                return ResourceManager.GetString("HomeMenu.Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saves.
        /// </summary>
        public static string HomeMenu_Saves {
            get {
                return ResourceManager.GetString("HomeMenu.Saves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string HomeMenu_Settings {
            get {
                return ResourceManager.GetString("HomeMenu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CryptoSoft Settings.
        /// </summary>
        public static string HomeMenu_Settings_CryptoSoft {
            get {
                return ResourceManager.GetString("HomeMenu.Settings.CryptoSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose an action:.
        /// </summary>
        public static string HomeMenu_Title {
            get {
                return ResourceManager.GetString("HomeMenu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to EasySave, the easiest to use backup application. To save data, simply go to the &quot;Create Save&quot; selection. If you have any problems please contact us at easysave.help@outlook.com.
        /// </summary>
        public static string HomePresentation {
            get {
                return ResourceManager.GetString("HomePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The most practical backup application.
        /// </summary>
        public static string HomeSubtitle {
            get {
                return ResourceManager.GetString("HomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to EasySave.
        /// </summary>
        public static string HomeWelcome {
            get {
                return ResourceManager.GetString("HomeWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English (USA).
        /// </summary>
        public static string Lang_en_US {
            get {
                return ResourceManager.GetString("Lang.en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string Lang_fr_FR {
            get {
                return ResourceManager.GetString("Lang.fr-FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italian.
        /// </summary>
        public static string Lang_it_IT {
            get {
                return ResourceManager.GetString("Lang.it-IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Russian.
        /// </summary>
        public static string Lang_ru_RU {
            get {
                return ResourceManager.GetString("Lang.ru-RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No item selected.
        /// </summary>
        public static string NoSelected {
            get {
                return ResourceManager.GetString("NoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect Path | .
        /// </summary>
        public static string Path_Invalid {
            get {
                return ResourceManager.GetString("Path.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup summary:.
        /// </summary>
        public static string Save_Info {
            get {
                return ResourceManager.GetString("Save.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run the save?.
        /// </summary>
        public static string Save_Run {
            get {
                return ResourceManager.GetString("Save.Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your saves :.
        /// </summary>
        public static string SaveMenu_Title {
            get {
                return ResourceManager.GetString("SaveMenu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CryptoSoft Extensions:.
        /// </summary>
        public static string Settings_Extensions {
            get {
                return ResourceManager.GetString("Settings.Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priority files.
        /// </summary>
        public static string Settings_Priority_Files {
            get {
                return ResourceManager.GetString("Settings.Priority-Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CryptoSoft Secret:.
        /// </summary>
        public static string Settings_Secret {
            get {
                return ResourceManager.GetString("Settings.Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Software package.
        /// </summary>
        public static string Settings_Software_Package {
            get {
                return ResourceManager.GetString("Settings.Software-Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change language.
        /// </summary>
        public static string SettingsMenu_ChangeLanguage {
            get {
                return ResourceManager.GetString("SettingsMenu.ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log file format.
        /// </summary>
        public static string SettingsMenu_LogsFormat {
            get {
                return ResourceManager.GetString("SettingsMenu.LogsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save created successfully.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
