@startuml ProSoft - CryptoSoft 1.0.0 - Class Diagram

title "ProSoft - CryptoSoft 1.0.0 - Class Diagram"

class CryptoSoft {
    - key : string
    - instance : CryptoSoft
    - stopwatch : Stopwatch
    - extensions : HashSet<String>

    - CryptoSoft()
    - CryptoSoft(key : string)
    - CryptoSoft(key : string, extensions : HashSet<String>)

    + {static} Init(key : string, extensions : string[]) : CryptoSoft
    + ProcessFile(inputFile : string, outputFile : string, largeFile : bool) : long
    + ProcessFiles(inputFiles : string[], outputDir : string) : Dictionnary<string, long>
}

@enduml