@startuml ProSoft - EasySave 2.0.0 - Class Diagram

title "ProSoft - EasySave 2.0.0 - Class Diagram"

class ViewModel {
    + CreateSave(name : string, src : string, dest : string, type : SaveType) : Save
    + EditSave(s : Save, newName : string) : void
    + DeleteSave(s : Save) : void
    + RunSave(s : Save) : string
    # StopAllSaves() : void
    + {static} IsUpToDate() : bool

    + GetSavesByUuid(names : HashSet<String>) : HashSet<Save>
    + GetSaves() : HashSet<string>
}

class Program <<static>> {
    - {static} Main() : void
}

package Render <<Folder>> {

    enum RenderMethod {
        Home
        CreateSave
        LoadSave
        EditSave
        DeleteSave
        ChangeLanguage
        Settings,
        ChangeLogsFormat
    }

    class View {
        - vm : ViewModel

        + View()

        + Start() : void
        + Render(type : RenderMethod) : void
        - RenderHome(message : string) : void
        - RenderCreateSave() : void
        - RenderEditSave(save : HashSet<Save>) : void
        - RenderLoadSave(save : HashSet<Save>) : void
        - RenderDeleteSave(save : HashSet<Save>) : void
        - RenderChangeLanguage() : void
        - RenderChangeLogsFormat() : void
        - RenderSettings() : void
        - PromptSave(multi : bool) : HashSet<Save>
        # Exit(code : int) : void
        - CheckUpdate() : string
    }

}

package Models <<Folder>> {

    Interface Dir {
        - path : string
    }

    class SrcDir {
        - size : double
        + nbFiles : long

        + SrcDir(path : string)

        + GetSize() : double
    }

    class DestDir {
        + DestDir(path : string)
    }

    package Exceptions <<Folder>> {
    
        class Exception {

        }

        class UnknownLogFormatException {

            + UnknownLogFormatException()
            + UnknownLogFormatException(message : string)
            + UnknownLogFormatException(message : string, inner : Exception)
            + UnknownLogFormatException(info : SerializationInfo, context : StreamingContext)
        } 

        class CantCheckUpdateException {

            + CantCheckUpdateException()
            + CantCheckUpdateException(message : string)
            + CantCheckUpdateException(message : string, inner : Exception)
            + CantCheckUpdateException(info : SerializationInfo, context : StreamingContext)
        } 

        class TooMuchSavesException {

            + TooMuchSavesException()
            + TooMuchSavesException(message : string)
            + TooMuchSavesException(message : string, inner : Exception)
            + TooMuchSavesException(info : SerializationInfo, context : StreamingContext)
        }

    }
    
    package Data <<Folder>> {

        abstract class Save {
            + {const} MAX_SAVES : int
            - {static} saves : Set<Save>
            + uuid : Guid
            - name : string
            - filesCopied : long
            - sizeCopied : long
            # status : JobStatus
            + SrcDir : SrcDir
            + DestDir : DestDir

            # Save(name: string, src : string, dest : string, guid : Guid, status : JobStatus)

            + {static} Create(name : string, src: Dir, dest : Dir, type : SaveType) : Save
            + Rename(newName : string) : void
            + Pause() : void
            + Resume() : void
            + Cancel() : void
            + Stop() : void
            + {static} Delete(uuid : Guid) : void
            + Run() : string
            + CalculateProgress() : int
            + {abstract} ToString() : string
            + {static} Init(data : dynamic) : void
            + AddFileCopied(nb : int) : void
            + AddSizeCopied(length : long) : void
            # ProcessResult(sw : StopWatch) : string
            + {static} GetSaves() : HashSet<save>
            + GetName() : string
            + GetStatus() : JobStatus
            + GetSizeCopied() : long
            + GetFilesCopied() : long
            + {abstract} GetSaveType() : SaveType
            + {static} GetStatus(status : String) : JobStatus
            - UpdateState() : void
        }            

        class DifferentialSave {
            # DifferentialSave(name : string, src: string, dest : string, guid : Guid, status : JobStatus)

            + GetSaveType() : SaveType
            + ToString() : string
        }

        class FullSave {
            # FullSave(name : string, src: string, dest : string, guid : Guid, status : JobStatus)

            + GetSaveType() : SaveType
            + ToString() : string
        }

        enum SaveType {
            Full
            Differential
        }

        enum JobStatus {
            Running
            Paused
            Finished
            Cancelled
            Error
            Waiting
        }
        
    }

    package Utils <<Folder>> {

        enum LogsFormat {
            JSON
            XML
        }

        class DirectoryUtils <<static>> {
            - {static} actualFile : string[]
            + {static} CopyFilesAndFolders(s : Save) : void
            - {static} CopyAll(s : Save, src : DirectoryInfo, dest : DirectoryInfo, type : SaveType) : void
            + {static} IsValidPath(path : string) : bool
            + {static} CreatePath(path : string) : void
            + {static} GetDirectorySize(dir : DirectoryInfo) : double
            + {static} GetDirectoryFiles(dir : DirectoryInfo) : long
            - {static} GetActualFile() : string[]
        }

        class LogUtils <<static>> {
            - {static} path : string
            - {static} date : string
            - {static} format : LogsFormat

            + {static} Init() : void
            + {static} LogSaves() : void
            - {static} SavesToJson() : JObject
            - {static} SavesToXml() : XElement
            + {static} SaveToJson(s : Save) : JObject
            + {static} SaveToXml(s : Save) : XElement
            + {static} LogTransfer(s : Save, sourcePath : stirng, destPath : String, fileSize : long, fileTransferTime : float) : void
            + {static} ChangeFormat(format : LogsFormat) : void
            + {static} GetFormat() : LogsFormat
        }

        class ConsoleUtils <<static>> {
            + {static} ChooseAction(title : string, choices : HashSet<string>, lastOption : string) : string
            + {static} ChooseMultiple(title : string, choices : HashSet<string>, lastOption : string) : string
            + {static} AskConfirm(withoutChoice : bool) : bool
            + {static} WriteJson(title : string, data : JsonText, color : Color) : void
            + {static} Ask(title : string, errorMessage : string) : string
            + {static} WriteError(error : string) : void
            + {static} CreateProgressBar(s : Save) : void
        }

        class VersionUtils <<static>> {
            + {static} GetVersionFromGit() : string
            + {static} VersionFromStr(version : string) : int[]
            + {static} CompareVersions() : bool
        }
    
    }

}

View "1..*" o------ "1" ViewModel
Save "*" *-- "1" SrcDir
Save "*" *-- "1" DestDir
Save "*" o------ "1" JobStatus

Dir <|.. SrcDir
Dir <|.. DestDir

Save <|.. FullSave
Save <|.. DifferentialSave

CantCheckUpdateException -up-|> Exception
TooMuchSavesException -up-|> Exception

/'Hidden links for organization'/
FullSave -down[hidden]-> JobStatus


@enduml