@startuml ProSoft - EasySave 1.0 - Class Diagram

title "ProSoft - EasySave 1.0 - Class Diagram"

class ViewModel {
    + ViewModel()

    + CreateSave() : void
    + LoadSave() : void
    + DeleteSave() : void
    + EditSave() : void
    + GetSaves() : HashSet<Save>
    + GetSaveBuUuid(name : String) : Save
}

class Program {
    - {static} Main() : void
}

class LogUtils <<static>> {
    - {static} path : string

    + {static} Init() : void
    + {static} LogSave(save : Save) : void
    + {static} LogTransfer(data : JObject) : void
    + {static} CalculateTransferTime() : long
    - {static} SavesToJson() : JObject
    + {static} SaveToJson(s : Save) : JObject
}

package Render <<Folder>> {

    enum RenderMethod {
        Home
        CreateSave,
        EditSave,
        DeleteSave,
        LoadSave
    }

    class View {
        - {readonly} vm : ViewModel

        + View()

        + Start() : void
        + Render(type : RenderMethod) : void
        - RenderHome(message : string) : void
        - RenderCreateSave() : void
        - RenderEditSave() : void
        - RenderLoadSave() : void
        - PromptSave() : Save
        - RenderDeleteSave(s : Save) : void
    }

}

package Models <<Folder>> {

    Interface Dir {
        - path : string
    }

    class SrcDir {
        - size : long
        - nbFiles : long

        + SrcDir(path : string)

        + CalculateSize() : long
        + CalculateNbFiles() : long
    }

    class DestDir {
        + DestDir(path : string)
    }

    package Data <<Folder>> {

        abstract class Save {
            + {const} MAX_SAVES = 5 : int
            - {static} saves : Set<Save>
            + {readonly} uuid : Guid
            + name : string
            - filesCopied : long
            - status : JobStatus
            + {readonly} SrcDir : SrcDir
            + {readonly} DestDir : DestDir

            # Save(name: string, src : string, dest : string, guid : Guid)

            + {static} GetSaves() : HashSet<save>

            + {static} Create(name : string, src: Dir, dest : Dir, type : SaveType) : Save
            + Rename(newName : string) : void
            + {static} Delete(uuid : Guid) : void
            + {abstract} Run (uuid : Guid) : void
            /'+ Pause() : void
            + Resume() : void
            + Cancel() : void'/
            - CalculateProgress() : int
            /'- CalculateRemainingTime() : int'/
            + GetFilesCopied() : long
            + GetStatus() : JobStatus
            + {abstract} ToString() : string
            + {abstract} GetSaveType() : SaveType
            + AddFileCopied() : void
            + {static} Init(jObject : JObject) : void
        }

        class DifferentialSave {
            # DifferentialSave(name : string, src: Dir, dest : Dir)

            + GetSaveType() : SaveType
            + Run() : Save
            + ToString() : string
        }

        class FullSave {
            # {internal} FullSave(name : string, src: Dir, dest : Dir)

            + GetSaveType() : SaveType
            + Run() : Save
            + ToString() : string
        }

        enum SaveType {
            Full
            Differential
        }

        enum JobStatus {
            Running
            Paused
            Finished
            Cancelled
            Error,
            Waiting
        }
        
    }

    class DirectoryUtils <<static>> {
        + {static} CopyFilesAndFolders(s : Save) : boolean
        + {static} CopyAll(s : Save, src : DirectoryInfo, dest : DirectoryInfo) : void
        + {static} IsValidPath(path : string) : boolean
        + {static} CreatePath(path : string) : void
    }

    class ConsoleUtils <<static>> {
        + {static} ChooseAction(title : string, choices : HashSet<string>, lastOption : string) : string
        + {static} AskConfirm() : boolean
        + {static} WriteJson(title : string, data : JsonText, color : Color) : void
        + {static} WriteError(error : string) : void
        +{static} CreateProgressBar(s : Save) : void
    }

}

View "1..*" o------ "1" ViewModel
Save "*" *-- "1" SrcDir
Save "*" *-- "1" DestDir
Save "*" o------ "1" JobStatus

Dir <|.. SrcDir
Dir <|.. DestDir

Save <|.. FullSave
Save <|.. DifferentialSave

@enduml