@startuml

title "ProSoft - EasySave 1.0 - Sequence Diagram - Save creation"

autonumber

participant View [
    v : View
]
participant ViewModel [
    vm : ViewModel
]
participant Save [
    s : Save
]
participant SrcDir [
    sd : SrcDir
]
participant DestDir [
    dd : DestDir
]



View -> ViewModel : Create a new save
ViewModel -> Save : Create a new save
SrcDir -> Save : Add a source directory
note left of SrcDir : Add a source path,\nthe size of the directory\nand the number of files in the directory
activate Save
DestDir -> Save : Add a destination directory
note left of DestDir : Add a destination path

Save -> Save : Creat the new save
note right of Save : Create a new save with the source and destination directories,\na name, an uuid,\nand a type like "Full" or "Differential"
Save --> ViewModel : Return the new save
deactivate Save
ViewModel --> View : Return the new save
@enduml